#!/usr/bin/env python

##-----------------------------
import os
import sys
import psana
import numpy as np
from time import time
#from Detector.PyDetector import PyDetector
from Detector.GlobalUtils import print_ndarr
from ImgAlgos.PyAlgos import reshape_nda_to_2d, reshape_nda_to_3d, print_arr_attr, print_arr
import pyimgalgos.GlobalGraphics as gg

from optparse import OptionParser
##-----------------------------

def example_01(dsname, source, ofname, events, evskip, plotim, verbos):

    SKIP   = evskip
    EVENTS = events + SKIP

    #dsname = 'exp=cxif5315:run=169'
    #src    = psana.Source('DetInfo(%s)' % source)
    src    = source
    if verbos : print 'Calibrated detector data average for\n  dataset: %s\n  source : %s' % (dsname, src)

    # Non-standard calib directory
    #psana.setOption('psana.calib-dir', './calib')

    ds  = psana.DataSource(dsname)
    evt = ds.events().next()
    env = ds.env()
    
    det = psana.Detector(src, env)
    shape = det.shape(evt) 

    print '  det.shape() = ', shape 
    
    #mask = det.mask(evt)
    
    t0_sec = time()
    counter=0
    arr_sum = np.zeros(shape, dtype=np.double)
    arr_max = np.zeros(shape, dtype=np.double)

    for i, evt in enumerate(ds.events()) :

        if i<SKIP    : continue
        if not i<EVENTS : break

        cdata = det.calib(evt)
        if cdata is None : continue
        if verbos and not i%10 : print '  Event: %d' % i
        counter += 1
        arr_sum += cdata 
        arr_max = np.maximum(arr_max, cdata)

    print '  Detector data found in %d events' % counter
    print '  Total consumed time = %f sec' % (time()-t0_sec)

    arr_ave = arr_sum/counter if counter>0 else arr_sum
  
    # Plot averaged image

    if plotim :
        #nda = arr_ave
        nda = arr_max
        img = det.image(evt, nda)
        if img is None : sys.exit('Image is not available. FURTHER TEST IS TERMINATED')
    
        ave, rms = nda.mean(), nda.std()
        gg.plotImageLarge(img, amp_range=(ave-1*rms, ave+3*rms))
        gg.show()

    # Save n-d array in text files

    suffix = source.replace(":","-").replace(".","-") #.lower()
    prefix = '%s-%s-r%04d-e%06d-%s' % (ofname, env.experiment(), evt.run(), counter, suffix)

    #det.save_txtnda('%s-ave.txt' % prefix, arr_ave, fmt='%.2f', verbos=True)
    #det.save_txtnda('%s-max.txt' % prefix, arr_max, fmt='%.2f', verbos=True)

    det.save_asdaq('%s-ave.txt' % prefix, arr_ave, fmt='%.2f', verbos=True)
    det.save_asdaq('%s-max.txt' % prefix, arr_max, fmt='%.2f', verbos=True)

    if det.is_cspad2x2() :
        from PSCalib.GeometryObject import two2x1ToData2x2 #, data2x2ToTwo2x1
        arr_daq = two2x1ToData2x2(arr_max)
        arr_daq.shape = (185*388, 2)
        print_ndarr(arr_daq, 'arr_daq')
        fname = '%s-max-noheader.txt' % prefix
        np.savetxt(fname, arr_daq, fmt='%.2f', delimiter=' ', newline='\n')
        print 'Saved file %s' % fname

#------------------------------

def usage() :
    return '\n\nExample of command to average n-d array from detector source and save it in file:\n'+\
           '\n         %prog -d <dataset> [-s <source>] [-f <file-prefix>]'+\
           ' [-n <events-collect>] [-m <events-skip>] [-p] [-v]'+\
           '\n  ex1:   %prog -d exp=cxif5315:run=169 -s CxiDs2.0:Cspad.0 -f nda-cspad -n 100 -m 0 -p -v'

##-----------------------------

def input_options_parser() :

    dsname_def = 'exp=cxif5315:run=169'
    source_def = 'CxiDs2.0:Cspad.0'
    ofname_def = 'nda'
    events_def = 100
    evskip_def = 0
    plotim_def = True       
    verbos_def = True       

    h_dsname = 'dataset name, default = %s' % dsname_def
    h_source = 'input ndarray file name, default = %s' % source_def
    h_ofname = 'output file prefix, default = %s' % ofname_def
    h_events = 'number of events to collect, default = %s' % events_def
    h_evskip = 'number of events to skip, default = %s' % evskip_def
    h_plotim = 'plot averaged image, default = %s' % str(plotim_def)
    h_verbos = 'verbosity, default = %s' % str(verbos_def)
    
    parser = OptionParser(description='Optional input parameters.', usage ='usage: %prog [options]' + usage())
    parser.add_option('-d', '--dsname', dest='dsname', default=dsname_def, action='store', type='string', help=h_dsname)
    parser.add_option('-s', '--source', dest='source', default=source_def, action='store', type='string', help=h_source)
    parser.add_option('-f', '--ofname', dest='ofname', default=ofname_def, action='store', type='string', help=h_ofname)
    parser.add_option('-n', '--events', dest='events', default=events_def, action='store', type='int',    help=h_events)
    parser.add_option('-m', '--evskip', dest='evskip', default=evskip_def, action='store', type='int',    help=h_evskip)
    parser.add_option('-p', '--plotim', dest='plotim', default=plotim_def, action='store_false',          help=h_plotim)
    parser.add_option('-v', '--verbos', dest='verbos', default=verbos_def, action='store_false',          help=h_verbos)
 
    (opts, args) = parser.parse_args()
    return (opts, args)

##-----------------------------

if __name__ == "__main__" :

    proc_name = os.path.basename(sys.argv[0])
    if len(sys.argv)==1 :
        print 'Try command: %s -h' % proc_name
        sys.exit ('End of %s' % proc_name)
        
    #print '%s\nExample # %d' % (80*'_', ntest)

    (opts, args) = input_options_parser()

    if opts.verbos :
        print 'Command arguments:', ' '.join(sys.argv)
        print '  opts: ', opts
        print '  args: ', args

    example_01(opts.dsname, opts.source, opts.ofname, opts.events, opts.evskip, opts.plotim, opts.verbos)

    sys.exit(0)

##-----------------------------
