#!/usr/bin/env python
#------------------------------
"""
  Prints epix10ka detector id for specified dataset and detector name pattern or alias.

  Created on 2018-09-19 by Mikhail Dubrovin
"""
#------------------------------

import logging
logger = logging.getLogger(__name__)

import sys
from Detector.AreaDetector import AreaDetector
from psana import DataSource #, Detector
from Detector.UtilsEpix import id_epix, get_epix10ka_config_object
from PSCalib.GlobalUtils import string_from_source

#------------------------------

DSNAME_DEF = 'exp=detdaq17:run=110'
DETNAME_DEF = ':Epix10ka.'
#DETNAME_DEF = 'DetLab.0:Epix10ka.0'

DSNAME  = sys.argv[1] if len(sys.argv) > 1 else DSNAME_DEF 
DETNAME = sys.argv[2] if len(sys.argv) > 2 else DETNAME_DEF

#------------------------------

def usage():
    return 'Usage: epix10ka_id <DSNAME> [<DETNAME>]'\
          +'\n  e.g. epix10ka_id exp=detdaq17:run=110 DetLab.0:Epix10ka.0'

#------------------------------

def jungfrau_id() :    
    logger.info('%s\nFinding epix10ka Id in dataset "%s" using name pattern %s' % (80*'_', DSNAME, DETNAME))
    if DSNAME==DSNAME_DEF and DETNAME==DETNAME_DEF: print usage()

    ds = DataSource(DSNAME)
    #det = Detector(DETNAME)
    env = ds.env()
    det = AreaDetector(DETNAME, env)
    c = get_epix10ka_config_object(env, det.source)
    panel_id = id_epix(c) 
    logger.info('epix10ka name: %s\nid: %s' % (det.pyda.str_src, panel_id))

#------------------------------

if __name__ == "__main__" :
    #logging.basicConfig(format='%(asctime)s %(name)s %(levelname)s: %(message)s', datefmt='%H:%M:%S', level=logging.DEBUG)
    logging.basicConfig(format='%(message)s', level=logging.DEBUG)
    jungfrau_id()

#------------------------------
