#!/usr/bin/env python

import os
import sys
from time import time

from Detector.GlobalUtils import info_command_line_parameters
from Detector.UtilsEpix10kaCalib import pedestals_calibration, CALIB_REPO_EPIX10KA, DIR_LOG_AT_START, GAIN_MODES_IN
from Detector.UtilsLogging import STR_LEVEL_NAMES, DICT_NAME_TO_LEVEL, init_logger, logging
from data_test.absolute_path import path_to_xtc_test_file
PATH_TO_XTC = path_to_xtc_test_file(fname='data-xcsl1004621-r0010-3events-epix10kaquad.xtc')
logger = logging.getLogger(__name__)
SCRNAME = sys.argv[0].split('/')[-1]

def raise_exception(cmt):
    raise IOError('WARNING: option %s MUST be specified.' % cmt)


def check_options(popts):
    if popts.det is None:
        raise_exception('"-d <detector-name>"')
    if popts.exp and popts.run is None:
        raise_exception('"-r <run-number> along with -e <experiment>"')
    if popts.exp is None and popts.run:
        raise_exception('"-e <experiment>" along with "-r <run-number>"')
    if popts.exp is None and popts.run is None and popts.dsnamex is None:
        raise_exception('"-e <experiment> -r <run-number>" or/and "-x <data-source>"')


def epix10ka_pedestals_calibration():

    t0_sec = time()

    parser = option_parser()
    (popts, pargs) = parser.parse_args()
    args = pargs
    opts = vars(popts)
    defs = vars(parser.get_default_values())

    check_options(popts)

    #logging.basicConfig(format='[%(levelname).1s] L%(lineno)04d: %(message)s', level=DICT_NAME_TO_LEVEL[popts.logmode])
    from Detector.UtilsCalib import RepoManager, cgu
    import getpass
    repoman = RepoManager(dirrepo=popts.dirrepo, dir_log_at_start=DIR_LOG_AT_START,\
                          dirmode=popts.dirmode, filemode=popts.filemode, group=popts.group)
    logname = repoman.logname('%s_%s' % (SCRNAME, getpass.getuser()))
    init_logger(loglevel=popts.logmode, logfname=logname, group=popts.group) # fmt='[%(levelname).1s] %(filename)s L%(lineno)04d %(message)s')
    logger.info('log file: %s' % logname)
    #logger.info('DIR_LOG_AT_START: %s' % DIR_LOG_AT_START)
    if popts.dirrepo != 'work':
        repoman.save_record_at_start(SCRNAME, adddict={'logfile':logname})

    pedestals_calibration(*args, **opts)

    os.chmod(logname, popts.filemode)
    cgu.change_file_ownership(logname, user=None, group=popts.group)

    logger.info('DONE, consumed time %.3f sec' % (time() - t0_sec))


def usage(mode=0):
    proc_name = os.path.basename(sys.argv[0])
    if   mode == 1: return 'Proceses dark run xtc data for epix10ka.'
    elif mode == 2: return 'Try: %s -h' % proc_name
    else: return\
           '\n%prog -e <experiment> [-d <detector>] [-r <run-number>]'\
           '\n     [-x <dsname-or-extension>] [-o <output-result-directory>] [-L <logging-mode>]'\
           '\nTEST COMMAND:'\
           '\n  %prog -e mfxx32516 -d NoDetector.0:Epix10ka.3 -r 1021 -n 2 -x :smd:dir=/reg/d/psdm/mfx/mfxx32516/.../xtc/ -o ./myrepo'\
           '\nREGULAR COMMAND:'\
           '\n  %prog -e mfxx32516 -d NoDetector.0:Epix10ka.3 -r 1021  -L INFO'\
           '\n  %prog -e xcsx35617 -d XcsEndstation.0:Epix10ka2M.0 -r394 -o ./work'\
           '\n  %prog -e xcslt5117 -d XcsEndstation.0:Epix10ka2M.0 -r19 -c1 -i15 -o ./work'\
           '\n  mpirun -n 5 epix10ka_pedestals_calibration -e xcslt5117 -d XcsEndstation.0:Epix10ka2M.0 -r19 -o ./work -L INFO'\
           '\n  %prog -d XcsEndstation.0:Epix10kaQuad.0 -e xcsl1004621 -r 10 -c 0 -x ' + PATH_TO_XTC + ' -o work'\


def option_parser():
    from optparse import OptionParser

    d_exp     = None # 'mfxx32516'
    d_det     = None # 'NoDetector.0:Epix10ka.3'
    d_run     = None # 1021 or 1021,1022-1025
    d_nbs     = 1024 # number of frames
    d_ccnum   = None
    d_ccmax   = 5
    d_idx     = None # 0-15 for epix10ka2m, 0-3 for epix10kaquad
    d_dsnamex = None # ':smd:dir=/reg/d/psdm/mfx/mfxx32516/scratch/.../xtc'
    d_dirrepo = CALIB_REPO_EPIX10KA # './myrepo'
    d_logmode = 'DEBUG'
    d_errskip = False
    d_dirmode  = 0o2775
    d_filemode = 0o664
    d_group    = 'ps-users'

    h_exp     = 'experiment name, default = %s' % d_exp
    h_det     = 'detector name, default = %s' % d_det
    h_run     = 'run number or list of runs ex. 12,14-18, default = %s' % str(d_run)
    h_nbs     = 'number of frames to calibrate pedestals, default = %s' % str(d_nbs)
    h_ccnum   = 'calibcycle number [0,4] or all by default, default = %s' % str(d_ccnum)
    h_ccmax   = 'maximal number of calib-cycles to process, default = %s' % str(d_ccmax)
    h_idx     = 'selected panel index (0-15/3 for epix10ka2m/quad) or all by default, default = %s' % str(d_idx)
    h_dsnamex = 'dataset string or xtc file name or extension after exp=<exp>:run=<run> beginning with colon ":", default = %s' % d_dsnamex
    h_dirrepo = 'repository for calibration results, default = %s' % d_dirrepo
    h_logmode = 'logging mode, one of %s, default = %s' % (STR_LEVEL_NAMES, d_logmode)
    h_errskip = 'flag to skip errors and keep processing (stop otherwise), default = %s' % d_errskip
    h_dirmode = 'mode for all mkdir, default = %s' % oct(d_dirmode)
    h_filemode= 'mode for all saved files, default = %s' % oct(d_filemode)
    h_group   = 'group ownership for all files, default = %s' % d_group

    parser = OptionParser(description=usage(1), usage = usage())
    parser.add_option('-e', '--exp',     default=d_exp,     action='store', type='string', help=h_exp)
    parser.add_option('-d', '--det',     default=d_det,     action='store', type='string', help=h_det)
    parser.add_option('-r', '--run',     default=d_run,     action='store', type='string', help=h_run)
    parser.add_option('-b', '--nbs',     default=d_nbs,     action='store', type='int',    help=h_nbs)
    parser.add_option('-c', '--ccnum',   default=d_ccnum,   action='store', type='int',    help=h_ccnum)
    parser.add_option('-m', '--ccmax',   default=d_ccmax,   action='store', type='int',    help=h_ccmax)
    parser.add_option('-i', '--idx',     default=d_idx,     action='store', type='int',    help=h_idx)
    parser.add_option('-x', '--dsnamex', default=d_dsnamex, action='store', type='string', help=h_dsnamex)
    parser.add_option('-o', '--dirrepo', default=d_dirrepo, action='store', type='string', help=h_dirrepo)
    parser.add_option('-L', '--logmode', default=d_logmode, action='store', type='string', help=h_logmode)
    parser.add_option('-E', '--errskip', default=d_errskip, action='store_true',           help=h_errskip)
    parser.add_option('--dirmode',       default=d_dirmode, action='store', type='int',    help=h_dirmode)
    parser.add_option('--filemode',      default=d_filemode,action='store', type='int',    help=h_filemode)
    parser.add_option('--group',         default=d_group,   action='store', type='string', help=h_group)

    return parser


if __name__ == "__main__":
    if len(sys.argv)==1: sys.exit('\n%s\n' % usage(2))
    else: epix10ka_pedestals_calibration()
    sys.exit(0)

# EOF
