#!/usr/bin/env python
#------------------------------
import os
import sys
from time import time

from Detector.GlobalUtils import info_command_line_parameters
from Detector.UtilsEpix10kaCalib import deploy_constants, CALIB_REPO_EPIX10KA, GAIN_MODES_IN

import logging
logger = logging.getLogger(__name__)
DICT_NAME_TO_LEVEL = {k:v for k,v in logging._levelNames.iteritems() if isinstance(k, str)}
STR_LEVEL_NAMES = ', '.join(DICT_NAME_TO_LEVEL.keys())

#------------------------------

def epix10ka_deploy_constants():

    t0_sec = time()

    parser = option_parser()
    (popts, pargs) = parser.parse_args()
    args = pargs
    opts = vars(popts)
    defs = vars(parser.get_default_values())

    if popts.exp is None : raise IOError('WARNING: option "-e <experiment>" MUST be specified.') # sys.exit()
    if popts.det is None : raise IOError('WARNING: option "-d <detector-name>" MUST be specified.')
    if popts.run is None : raise IOError('WARNING: option "-r <run-number>" MUST be specified.')

    logging.basicConfig(format='%(levelname)s: %(message)s', level=DICT_NAME_TO_LEVEL[popts.logmode])
    
    logger.debug('%s\nIn epix10ka_deploy_constants' % (50*'_'))
    logger.debug(info_command_line_parameters(parser))

    deploy_constants(*args, **opts)

    logger.info('DONE, consumed time %.3f sec' % (time() - t0_sec))

#------------------------------

def usage(mode=0) :
    proc_name = os.path.basename(sys.argv[0])
    if   mode == 1 : return 'For specified run or timstamp combine gain constants from repository and deploy them in the calib directory'
    elif mode == 2 : return 'Try: %s -h' % proc_name
    else : return\
           '\n%prog -e <experiment> [-d <detector>] [-r <run-number>] [-L <logging-mode>] [-D] [...]'\
           '\nTEST COMMAND:'\
           '\n  %prog -e mfxx32516 -d NoDetector.0:Epix10ka.3 -r 1021 -t 20180910111049 -x /reg/d/psdm/mfx/mfxx32516/scratch/gabriel/pulser/xtc/combined -o ./myrepo -c ./calib -L info -D'\
           '\nREGULAR COMMAND:'\
           '\n  %prog -e mfxx32516 -d NoDetector.0:Epix10ka.3 -r 1021 -D -L INFO'\
           '\n  %prog -e xcsx35617 -d XcsEndstation.0:Epix10ka2M.0 -r394 -t 396 -o ./work -D -c ./calib # deploys 394-end.data for all calibrations found for runs <= 386'\
           '\n  %prog -e xcsx35617 -d XcsEndstation.0:Epix10ka2M.0 -r544 -o ./work -D -c ./calib'\
           '\n  %prog -e xcsx35617 -d XcsEndstation.0:Epix10ka2M.0 -r544 -o ./work -D -c ./calib --proc=g --low=0.25 --medium=1 --high=1'

#------------------------------

def option_parser() :
    from optparse import OptionParser

    d_exp     = None # 'mfxx32516'
    d_det     = None # 'NoDetector.0:Epix10ka.3'
    d_run     = None # 1021
    d_tstamp  = None # 20180910111049
    d_dirxtc  = None # '/reg/d/psdm/mfx/mfxx32516/scratch/gabriel/pulser/xtc/combined'
    d_dirrepo = CALIB_REPO_EPIX10KA # './myrepo' 
    d_dircalib= None # './calib
    d_deploy  = False
    d_logmode = 'DEBUG'
    d_gainci  = False
    d_proc    = 'psrg'
    d_high    = 16.40 # 1.
    d_medium  = 5.466 # 0.33333
    d_low     = 0.164 # 0.01
    #Blaj, Gabriel <blaj@slac.stanford.edu> Mon 8/3/2020 6:52 PM
    #Hi, Here are some good starting values for the ADC to keV conversion:
    #High gain: 132 ADU / 8.05 keV = 16.40 ADU/keV
    #Medium gain: 132 ADU / 8.05 keV / 3 = 5.466 ADU/keV
    #Low gain: 132 ADU / 8.05 keV / 100 = 0.164 ADU/keV

    h_exp     = 'experiment name, default = %s' % d_exp
    h_det     = 'detector name, default = %s' % d_det
    h_run     = 'run number for beginning of the validity range, default = %s' % str(d_run)
    h_tstamp  = 'non-default time stamp (<YYYYmmddHHMMSS) or run number(<10000) for constants selection in repo. '\
                'By default run time is used, default = %s' % str(d_tstamp)
    h_dirxtc  = 'non-default xtc directory which is used to access run start time, default = %s' % d_dirxtc
    h_dirrepo = 'non-default repository of calibration results, default = %s' % d_dirrepo
    h_dircalib= 'deployment calib directory if different from standard one, default = %s' % d_dircalib
    h_deploy  = 'deploy constants to the calib dir, default = %s' % d_deploy
    h_logmode = 'logging mode, one of %s, default = %s' % (STR_LEVEL_NAMES, d_logmode)
    h_high    = 'default high   gain ADU/keV, default = %s' % str(d_high)
    h_medium  = 'default medium gain ADU/keV, default = %s' % str(d_medium)
    h_low     = 'default low    gain ADU/keV, default = %s' % str(d_low)
    h_gainci  = 'deploy gain constants evaluated in charge injection OVERRIDES regular gain, default = %s' % d_gainci
    h_proc    = '(str) keyword for processing of "p"-pedestals, "r"-rms, "s"-status, "g" or "c" - gain or charge-injection gain,'\
              + '  default = %s' % d_proc

    parser = OptionParser(description=usage(1), usage = usage())
    parser.add_option('-e', '--exp',     default=d_exp,     action='store', type='string', help=h_exp)
    parser.add_option('-d', '--det',     default=d_det,     action='store', type='string', help=h_det)
    parser.add_option('-r', '--run',     default=d_run,     action='store', type='int',    help=h_run)
    parser.add_option('-t', '--tstamp',  default=d_tstamp,  action='store', type='int',    help=h_tstamp)
    parser.add_option('-x', '--dirxtc',  default=d_dirxtc,  action='store', type='string', help=h_dirxtc)
    parser.add_option('-o', '--dirrepo', default=d_dirrepo, action='store', type='string', help=h_dirrepo)
    parser.add_option('-c', '--dircalib',default=d_dircalib,action='store', type='string', help=h_dircalib)
    parser.add_option('-D', '--deploy',  default=d_deploy,  action='store_true',           help=h_deploy)
    parser.add_option('-L', '--logmode', default=d_logmode, action='store', type='string', help=h_logmode)
    parser.add_option(      '--high',    default=d_high,    action='store', type='float',  help=h_high)
    parser.add_option(      '--medium',  default=d_medium,  action='store', type='float',  help=h_medium)
    parser.add_option(      '--low',     default=d_low,     action='store', type='float',  help=h_low)
    parser.add_option('-p', '--proc',    default=d_proc,    action='store', type='string', help=h_proc)
    #parser.add_option('-g', '--gainci',  default=d_gainci,  action='store_true',           help=h_gainci)

    return parser

#------------------------------

if __name__ == "__main__" :
    if len(sys.argv)==1 : print '\n%s\n' % usage(2)
    else : epix10ka_deploy_constants()
    sys.exit(0)

#------------------------------
